// site-data.js: the content behind the CSS 343 hub's extras (the rotating pictures, the xkcd panel,
// the quote and the "did you know?" fact). Plain data, no imports; lib/site-extras.js reads it.
// Every quote and fact carries its source. Checked 2026-09-30; a story that is told more than one
// way is phrased as such.

// ── the pictures: made for this course ──
export const PICS = [
  { id: "fruit-tree", img: "media/pics/fruit-tree.jpg", title: "A fruit tree on a heap", sub: "drawn for this course",
    credit: "Drawn for CSS 343 as SVG by media/fruit_tree.py.",
    facts: [
      { t: "The tree is a binary search tree drawn upside down: the root, 99, is at the bottom and its single child, 50, sits at the top of the long trunk edge. Read the fruit left to right and the keys come out in order: 6, 12, 18, 25, 31, 37, 43, 50, 56, 62, 68, 75, 81, 87, 93.", src: "course text, Trees and Binary Search Trees" },
      { t: "Every key in the root's subtree is smaller than 99, so the root has no right child at all. A search for any of the other fifteen keys goes up the trunk first.", src: "course text, Trees and Binary Search Trees" },
      { t: "The stones are a min-heap: every stone is no larger than the two stones beneath it, so the smallest, 1, is on top. Stored level by level the heap is the array 1, 2, 3, ..., 15, and the children of position i are at positions 2i and 2i + 1.", src: "course text, Heaps and Priority Queues" },
      { t: "The monkey sits on the edge from 50 to its left child and reaches for that child, 25: the root of the subtree that holds every key smaller than 50.", src: "course text, Trees and Binary Search Trees" },
    ] },
  { id: "lemur-tree-1", img: "media/pics/lemur-tree-1.jpg", title: "The lemur and the search tree", sub: "made for this course",
    credit: "Made for CSS 343 with an image generator.",
    facts: [
      { t: "Fifteen fruit, fifteen keys, and a valid binary search tree: every key in a node's left subtree is smaller and every key in its right subtree is larger. In order, the keys read 10, 20, 25, 30, 35, 40, 45, 50, 80, 90, 95, 100, 105, 110, 120.", src: "checked against the picture; course text, Trees and Binary Search Trees" },
      { t: "The tree is perfect: every level full, height 4 counting nodes. Fifteen keys cannot be stored in a binary tree of fewer than four levels, since three levels hold at most 7.", src: "course text, Trees and Binary Search Trees" },
      { t: "Searching for the durian, 120, takes four comparisons: 50, then 100, then 110, then 120.", src: "course text, Trees and Binary Search Trees" },
    ] },
  { id: "lemur-tree-2", img: "media/pics/lemur-tree-2.jpg", title: "The same tree, in daylight", sub: "made for this course",
    credit: "Made for CSS 343 with an image generator.",
    facts: [
      { t: "The same fifteen keys as the night version. Inserting them in the order 10, 20, 25, ... 120 instead of root first would have built a chain fifteen nodes tall, one child per node.", src: "course text, Trees and Binary Search Trees; AVL Trees" },
      { t: "A balanced search tree, such as an AVL or red-black tree, would rotate that chain back into a shape like this one as the keys arrive.", src: "course text, AVL Trees; Red-Black Trees" },
    ] },
  { id: "lemur-tree-3", img: "media/pics/lemur-tree-3.jpg", title: "An orchard of nodes", sub: "made for this course",
    credit: "Made for CSS 343 with an image generator.",
    facts: [
      { t: "An early study for the course picture: a monkey in a fruit tree whose roots run down into a row of crates.", src: "made for this course" },
      { t: "Graphs in general are allowed cycles; a tree is a connected graph with no cycle, which is why a tree on n nodes always has exactly n - 1 edges.", src: "course text, Graphs: Vocabulary and Representations" },
    ] },
];

// ── "did you know?" ──
export const FACTS = [
  { topic: "recursion", t: "Binary search was first published in 1946, but a version correct for every array size did not appear in print until 1962. In 2006 Joshua Bloch reported that Java's own library binary search had overflowed for years on huge arrays, because it computed the middle as (low + high) / 2.",
    src: "Knuth, The Art of Computer Programming, vol. 3, §6.2.1; Bloch, Google Research blog, 2006, https://research.google/blog/extra-extra-read-all-about-it-nearly-all-binary-searches-and-mergesorts-are-broken/" },
  { topic: "analysis", t: "No known algorithm solves 3-sum in time that beats n² by more than a logarithmic factor; whether one exists is an open problem, and many geometry problems are known to be at least as hard.",
    src: "Grønlund and Pettie, “Threesomes, Degenerates, and Love Triangles,” FOCS 2014; Gajentaan and Overmars, 1995" },
  { topic: "sorting", t: "John von Neumann wrote a merge sort in 1945, one of the first programs written for a stored-program computer.",
    src: "Knuth, The Art of Computer Programming, vol. 3, §5.2.4" },
  { topic: "sorting", t: "Tony Hoare invented quicksort around 1959 while working on machine translation in Moscow, as a way to sort the words of a sentence before looking them up.",
    src: "Hoare, “Quicksort,” The Computer Journal 5(1), 1962; Hoare's oral history, Computer History Museum" },
  { topic: "sorting", t: "Any sort that only compares keys needs at least log₂(n!) comparisons in the worst case. For 5 keys that is 7, since 5! = 120 is more than 2⁶ = 64, and 7 comparisons are enough.",
    src: "course text, The Sorting Lower Bound; Knuth, TAOCP vol. 3, §5.3.1" },
  { topic: "trees", t: "AVL trees, the first self-balancing search trees, are named for Georgy Adelson-Velsky and Evgenii Landis, who published them in 1962.",
    src: "Adelson-Velsky and Landis, “An algorithm for the organization of information,” 1962" },
  { topic: "trees", t: "Red-black trees come from Leonidas Guibas and Robert Sedgewick (1978). Sedgewick has said the colors were red and black because those printed best on the laser printer they had at Xerox PARC.",
    src: "Guibas and Sedgewick, FOCS 1978; Sedgewick, Algorithms, Part I lectures (Princeton / Coursera)" },
  { topic: "trees", t: "C++'s std::map and std::set are red-black trees in both of the major standard libraries, libstdc++ and libc++.",
    src: "libstdc++ bits/stl_tree.h; libc++ __tree" },
  { topic: "trees", t: "Rudolf Bayer and Edward McCreight invented the B-tree at Boeing in 1970. They never said what the B stands for; balanced, broad, Boeing and Bayer have all been proposed.",
    src: "Bayer and McCreight, Acta Informatica 1, 1972; Comer, “The Ubiquitous B-Tree,” Computing Surveys, 1979" },
  { topic: "heaps", t: "The binary heap and heapsort were published by J. W. J. Williams in 1964. The same year Robert Floyd showed a heap can be built in linear time, by sinking from the last internal node up.",
    src: "Williams, “Algorithm 232: Heapsort,” CACM 1964; Floyd, “Algorithm 245: Treesort 3,” CACM 1964" },
  { topic: "hashing", t: "Hans Peter Luhn of IBM described hashing with chained buckets in an internal memo in January 1953.",
    src: "Knuth, The Art of Computer Programming, vol. 3, §6.4" },
  { topic: "graphs", t: "Graph theory begins with Leonhard Euler's 1736 proof that no walk crosses each of Königsberg's seven bridges exactly once.",
    src: "Euler, “Solutio problematis ad geometriam situs pertinentis,” 1736" },
  { topic: "graphs", t: "Edsger Dijkstra designed his shortest-path algorithm in 1956 in about twenty minutes, sitting at a café terrace in Amsterdam, without pencil and paper.",
    src: "Frana and Misa, “An Interview with Edsger W. Dijkstra,” CACM 53(8), 2010" },
  { topic: "graphs", t: "The first minimum spanning tree algorithm was Otakar Borůvka's in 1926, for laying out an electrical network in Moravia. Vojtěch Jarník found the algorithm now called Prim's in 1930, 27 years before Prim.",
    src: "Graham and Hell, “On the History of the Minimum Spanning Tree Problem,” Annals of the History of Computing, 1985" },
  { topic: "graphs", t: "With union by rank and path compression, union-find costs O(α(n)) per operation, where α, the inverse Ackermann function, is at most 4 for any n that could be written down in this universe.",
    src: "Tarjan, “Efficiency of a Good But Not Linear Set Union Algorithm,” JACM 1975; course text, Union-Find" },
  { topic: "greedy", t: "David Huffman found his code in 1951 as a term paper for Robert Fano's information theory class at MIT; the paper was the alternative to taking the final exam.",
    src: "Stix, “Profile: David A. Huffman,” Scientific American, September 1991" },
  { topic: "dp", t: "Richard Bellman picked the name dynamic programming in the early 1950s partly because it sounded impressive and could not be used as a pejorative, at a time when the Secretary of Defense disliked the word research.",
    src: "Bellman, Eye of the Hurricane: An Autobiography, 1984" },
  { topic: "strings", t: "Edward Fredkin coined the word trie in 1960, from retrieval, and pronounced it “tree”. Most people now say “try” so the two can be told apart.",
    src: "Fredkin, “Trie Memory,” CACM 3(9), 1960" },
  { topic: "strings", t: "The Knuth-Morris-Pratt algorithm was found independently by James Morris and by Donald Knuth with Vaughan Pratt; the three published it together in 1977.",
    src: "Knuth, Morris and Pratt, “Fast Pattern Matching in Strings,” SIAM J. Computing 6(2), 1977" },
  { topic: "strings", t: "Stephen Kleene introduced regular expressions in 1951 to describe what McCulloch and Pitts's model neurons could recognize. Ken Thompson put them into a text editor in 1968 by compiling each one to an automaton.",
    src: "Kleene, RAND Memorandum RM-704, 1951; Thompson, “Regular Expression Search Algorithm,” CACM 11(6), 1968" },
  { topic: "strings", t: "grep is named after the ed editor command g/re/p: globally search for a regular expression and print the matching lines.",
    src: "Kernighan, UNIX: A History and a Memoir, 2019" },
];

// ── quotes ──
export const QUOTES = [
  { q: "Premature optimization is the root of all evil.", who: "Donald Knuth", src: "Structured Programming with go to Statements, 1974" },
  { q: "Programs must be written for people to read, and only incidentally for machines to execute.", who: "Harold Abelson and Gerald Jay Sussman", src: "Structure and Interpretation of Computer Programs, preface" },
  { q: "Controlling complexity is the essence of computer programming.", who: "Brian Kernighan", src: "Software Tools, 1976" },
  { q: "Everyone knows that debugging is twice as hard as writing a program in the first place. So if you're as clever as you can be when you write it, how will you ever debug it?", who: "Brian Kernighan", src: "The Elements of Programming Style, 1974" },
  { q: "The purpose of computing is insight, not numbers.", who: "Richard Hamming", src: "Numerical Methods for Scientists and Engineers, 1962" },
  { q: "Simplicity is prerequisite for reliability.", who: "Edsger W. Dijkstra", src: "EWD498, 1975" },
  { q: "An algorithm must be seen to be believed.", who: "Donald Knuth", src: "The Art of Computer Programming, vol. 1" },
  { q: "Bad programmers worry about the code. Good programmers worry about data structures and their relationships.", who: "Linus Torvalds", src: "git mailing list, 2006" },
  { q: "Beware of bugs in the above code; I have only proved it correct, not tried it.", who: "Donald Knuth", src: "memo to Peter van Emde Boas, 1977" },
  { q: "Algorithms + Data Structures = Programs", who: "Niklaus Wirth", src: "the title of his 1976 book" },
  { q: "Rules of Optimization: Rule 1: Don't do it. Rule 2 (for experts only): Don't do it yet.", who: "Michael A. Jackson", src: "Principles of Program Design, 1975" },
];

// ── xkcd, by Randall Munroe, CC BY-NC 2.5 (https://xkcd.com/license.html) ──
export const COMICS = [
  { num: 208, title: "Regular Expressions", alt: "Wait, forgot to escape a space.  Wheeeeee[taptaptap]eeeeee.",
    img: "media/xkcd/208.png" },
  { num: 303, title: "Compiling", alt: "'Are you stealing those LCDs?' 'Yeah, but I'm doing it while my code compiles.'",
    img: "media/xkcd/303.png" },
  { num: 399, title: "Travelling Salesman Problem", alt: "What's the complexity class of the best linear programming cutting-plane techniques?  I couldn't find it anywhere.  Man, the Garfield guy doesn't have these problems ...",
    img: "media/xkcd/399.png" },
  { num: 835, title: "Tree", alt: "Not only is that terrible in general, but you just KNOW Billy's going to open the root present first, and then everyone will have to wait while the heap is rebuilt.",
    img: "media/xkcd/835.png" },
  { num: 974, title: "The General Problem", alt: "I find that when someone's taking time to do something right in the present, they're a perfectionist with no ability to prioritize, whereas when someone took time to do something right in the past, they're a master artisan of great foresight.",
    img: "media/xkcd/974.png" },
  { num: 1171, title: "Perl Problems", alt: "To generate #1 albums, 'jay --help' recommends the -z flag.",
    img: "media/xkcd/1171.png" },
  { num: 1185, title: "Ineffective Sorts", alt: "StackSort connects to StackOverflow, searches for 'sort a list', and downloads and runs code snippets until the list is sorted.",
    img: "media/xkcd/1185.png" },
  { num: 1195, title: "Flowchart", alt: "The way out is to use the marker you have to add a box that says 'get a marker' to the line between you and 'start', then add a 'no' line from the trap box to 'end'.",
    img: "media/xkcd/1195.png" },
  { num: 1270, title: "Functional", alt: "Functional programming combines the flexibility and power of abstract mathematics with the intuitive clarity of abstract mathematics.",
    img: "media/xkcd/1270.png" },
  { num: 1445, title: "Efficiency", alt: "I need an extension for my research project because I spent all month trying to figure out whether learning Dvorak would help me type it faster.",
    img: "media/xkcd/1445.png" },
  { num: 1597, title: "Git", alt: "If that doesn't fix it, git.txt contains the phone number of a friend of mine who understands git. Just wait through a few minutes of 'It's really pretty simple, just think of branches as...' and eventually you'll learn the commands that will fix everything.",
    img: "media/xkcd/1597.png" },
  { num: 1691, title: "Optimization", alt: "Premature optimization is the root of all evil, so to start this project I'd better come up with a system that can determine whether a possible optimization is premature or not.",
    img: "media/xkcd/1691.png" },
  { num: 2347, title: "Dependency", alt: "Someday ImageMagick will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble.",
    img: "media/xkcd/2347.png" },
];
